# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-26 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHoursSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('instructor_code', models.SlugField(blank='', max_length=6)),
                ('student_code', models.SlugField(blank='', max_length=6)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
        ),
    ]
