# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-26 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_number', '0003_remove_officehourssession_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officehourssession',
            name='instructor_code',
        ),
    ]
