# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-26 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_number', '0005_auto_20181125_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officehourssession',
            old_name='instructor_code',
            new_name='instructorCode',
        ),
        migrations.RenameField(
            model_name='officehourssession',
            old_name='student_code',
            new_name='studentCode',
        ),
    ]
