# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-09 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_number', '0006_auto_20181125_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(blank='', primary_key=True, serialize=False)),
                ('school', models.CharField(blank='', max_length=200)),
                ('course_name', models.CharField(blank='', max_length=200)),
                ('course_abbr', models.CharField(blank='', max_length=200)),
                ('email', models.EmailField(blank='', max_length=200)),
                ('ta_join_code', models.SlugField(blank='', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='OfficeHoursSession',
        ),
    ]
