# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-09 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_number', '0007_auto_20181209_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_abbr',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='ta_join_code',
            new_name='teachingAssistantJoinCode',
        ),
    ]
